In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


# import numpy

In [1]:
import numpy as np

In [8]:
numList = [5,1,3]

In [9]:
floatList = [5.3, 1.1, 3.4]

In [10]:
textList = ['harry', 'sahil', 'ujjwal']

In [11]:
boolList = [True, False, True]

In [12]:
numArr = np.array(numList)

In [13]:
print(numArr)

[5 1 3]


In [14]:
numArr

array([5, 1, 3])

In [15]:
floatList

[5.3, 1.1, 3.4]

In [16]:
floatArr = np.array(floatList)

In [17]:
floatArr.dtype

dtype('float64')

In [18]:
floatArr

array([5.3, 1.1, 3.4])

In [19]:
print(floatArr)

[5.3 1.1 3.4]


In [20]:
textArr = np.array(textList)

In [21]:
textArr

array(['harry', 'sahil', 'ujjwal'], dtype='<U6')

In [22]:
textArr.dtype

dtype('<U6')

In [24]:
boolArr = np.array(boolList)

In [25]:
boolArr

array([ True, False,  True])

In [26]:
boolArr.dtype

dtype('bool')

In [27]:
print(boolArr)

[ True False  True]


In [29]:
np.array([5,6.3, True, 'happy'])

array(['5', '6.3', 'True', 'happy'], dtype='<U32')

In [32]:
arr = np.array([45, 5, 6, 7, 3, 9, 45, 23, 89, 98, 5])

In [33]:
arr

array([45,  5,  6,  7,  3,  9, 45, 23, 89, 98,  5])

In [34]:
print(arr)

[45  5  6  7  3  9 45 23 89 98  5]


In [35]:
arr.ndim

1

In [36]:
# give counting of total 
arr.size

11

In [37]:
arr.shape

(11,)

# scalar
### which consists only single value either it is int or string

In [58]:
scalar = np.array(['harry'])

In [59]:
scalar

array(['harry'], dtype='<U5')

In [60]:
print(scalar)

['harry']


In [61]:
scalar.dtype

dtype('<U5')

In [62]:
scalar.shape

(1,)

In [63]:
scalar.size

1

In [64]:
scalar.ndim

1

# vector
### it consists sequence of numbers

In [67]:
vector = np.array([5,2,3,5])

In [68]:
vector

array([5, 2, 3, 5])

In [69]:
print(vector)

[5 2 3 5]


In [70]:
vector.ndim

1

In [54]:
vector.size

4

In [55]:
vector.shape

(4,)

# matrix
    it is a collection of lot of vector

In [65]:
matrix = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
        
    ]
)

In [66]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
matrix.size

9

In [68]:
matrix.shape

(3, 3)

In [69]:
matrix.ndim

2

In [70]:
matrix.dtype

dtype('int64')

In [71]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [72]:
matrix = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
)

In [73]:
matrix.ndim

2

In [74]:
matrix.shape

(3, 4)

In [75]:
matrix.size

12

In [77]:
matrix.dtype

dtype('int64')

In [78]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Tensor
### it is a multi-dimensional array

In [72]:
tensor = np.array([
    [
        [1,2],
        [3,4]
    ],

    [
        [5,6],
        [7,8]
    ],

    [
        [9,10],
        [11,12]
    ]
    ])
    

In [73]:
tensor.shape

(3, 2, 2)

In [87]:
tensor.size

12

In [88]:
tensor.ndim

3

In [89]:
print(tensor)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [90]:
tensor.dtype

dtype('int64')

In [191]:
tensor = np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],

    [
        [9,10,11,12],
        [13,14,15,16]
    ],

    [
        [17,18,19,20],
        [21,22,23,24]
    ],

    [
        [25,26,27,28],
        [29,30,31,32]
    ],

    [
        [33,34,35,36],
        [37,38,39,40]
    ]

    
])

In [219]:
tensor.shape

(5, 2, 4)

In [220]:
tensor.size

40

In [221]:
tensor.ndim

3

In [222]:
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]]]


# Reshape
### it means changing the shape without changing array's data

In [105]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [106]:
arr.dtype

dtype('int64')

In [107]:
arr.shape

(12,)

In [108]:
arr.size

12

In [109]:
arr.ndim

1

In [114]:
arr.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [111]:
arr.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
arr.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [116]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [117]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [118]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [139]:
arr = np.array([x for x in range(1,25)])

In [140]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [142]:
# ( -1 ) इसे हम "unknown dimension" या "auto-infer dimension" भी कह सकते हैं।
arr.reshape(4, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [149]:
arr.reshape(2, 3, -1)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [154]:
arr.reshape(3,4,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [188]:
arr = np.array([x for x in range(1,41)])

In [189]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [208]:
arr.reshape(4, 10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [209]:
arr.reshape(2, 20)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40]])

In [210]:
arr.reshape(5,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [223]:
arr.reshape(5,8,-1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16]],

       [[17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]],

       [[25],
        [26],
        [27],
        [28],
        [29],
        [30],
        [31],
        [32]],

       [[33],
        [34],
        [35],
        [36],
        [37],
        [38],
        [39],
        [40]]])

In [224]:
arr.reshape(5,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40]]])

In [254]:
arr = np.array([1,2,3,4,5,6,7,8,10,11,12,13,14,15])

In [255]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15])

In [260]:
arr = arr[2:11]

In [261]:
arr

array([ 3,  4,  5,  6,  7,  8, 10, 11, 12])

In [262]:
arr.reshape(3,3)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12]])

In [263]:
arr.reshape(9,-1)

array([[ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [10],
       [11],
       [12]])

In [13]:
# 2D array
arr = np.array([[1,2,3], [1,2,3], [1,2,3]])

In [5]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [6]:
arr.shape

(3, 3)

In [9]:
arr = np.array([[1,2], [1,2], [1,2]])

In [10]:
arr.shape

(3, 2)

In [11]:
arr

array([[1, 2],
       [1, 2],
       [1, 2]])

In [12]:
arr.ndim

2

In [22]:
# 3D array
# when we include multiple 2D array the we'll get 3D array
arr = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])

In [24]:
arr.shape

(2, 2, 3)

In [23]:
arr

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [45]:
arr = np.array([
    [
        [1,2,3]
    ],

    [
        [1,2,3]
    ],

    [
        [1,2,3]
    ],

    [
        [1,2,3]
    ]
 ])

In [46]:
arr

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [47]:
arr.shape

(4, 1, 3)

In [48]:
arr = np.array([
    [
        [1,2],
        [3,4]
    ],

    [
        [5,6],
        [7,8]
    ],

    [
        [9,10],
        [11,12]
    ],

    [
        [13,14],
        [15,16]
    ]
])

In [49]:
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [50]:
arr.shape

(4, 2, 2)

In [55]:
arr = np.array([
    [
        [1,2,3,4,5,6],
        [7,8,9,10,11,12]
    ],

    [
        [13,14,15,16,17,18],
        [19,20,21,22,23,24]
    ],

    [
        [25,26,27,28,29,30],
        [31,32,33,34,35,36]
    ]
])

In [56]:
arr

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]]])

In [57]:
arr.shape

(3, 2, 6)

In [11]:
arr= np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],

    [
        [9,10,11,12],
        [13,14,15,16]
    ],

    [
        [17,18,19,20],
        [21,22,23,24]
    ],

    [
        [25,26,27,28],
        [29,30,31,32]
    ]
    ])

In [12]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [13]:
arr.size

32

In [14]:
arr.shape

(4, 2, 4)

In [20]:
### scalar addition concept
array1 = np.array([1,2,3,4,5,6])

In [21]:
array2 = array1 +5

In [22]:
print(array1)

[1 2 3 4 5 6]


In [23]:
print(array2)

[ 6  7  8  9 10 11]


In [24]:
array1 = np.array([7,8,9,5])

In [25]:
array2 = array1 +3

In [26]:
print(array1)

[7 8 9 5]


In [27]:
print(array2)

[10 11 12  8]


In [29]:
# Ek NumPy array banaate hain
array1 = np.array([5,3,8,2])

# Scalar addition use kiya
array2 = array1 + 7

print(array1) # original array print kiya
print(array2) # array 2 print kiya jisme 7 add hua

[5 3 8 2]
[12 10 15  9]


In [40]:
arr = np.array([x for x in range(1,19)])

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [48]:
arr.reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [50]:
arr = np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ]
)

In [51]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
arr.shape

(2, 5)

In [57]:
arr = np.array(
    [
        [18,17,16,15],
        [14,13,12,11],
        [10,9,8,7],
        [6,5,4,3]
    ]
)

In [58]:
arr.shape

(4, 4)

In [59]:
arr = np.array([
    [
        [30,29,28,27],
        [26,25,24,23]
    ],

    [
        [22,21,20,19],
        [18,17,16,15]
    ],

    [
        [14,13,12,11],
        [10,9,8,7]
    ]
])

In [61]:
arr.shape

(3, 2, 4)

In [66]:
arr.reshape(2,2)

ValueError: cannot reshape array of size 24 into shape (3,2,2)