In [1]:
import numpy as np

In [2]:
arr = np.array(range(25))

In [3]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
arr = np.array(range(24))

In [112]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [113]:
arr = arr.reshape(2,3,4)

In [114]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [115]:
arr.ndim

3

In [116]:
arr.shape

(2, 3, 4)

In [117]:
arr.ndim

3

# Arange generates a array with numbers in a range

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr.shape

(25,)

In [35]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### generates numbers linearly spaced from starting index including index

In [118]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [119]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### random functions

### generates array random numbers from uniform distribution between 0 and 1

In [40]:
np.random.rand(5)

array([0.90687831, 0.76021074, 0.00409872, 0.65903168, 0.69867716])

In [42]:
np.random.rand(5, 3)

array([[0.71996596, 0.23283274, 0.17596757],
       [0.04085985, 0.90642605, 0.28376935],
       [0.81571943, 0.50666199, 0.16586838],
       [0.87240542, 0.70091892, 0.75841227],
       [0.94528317, 0.01450776, 0.48399895]])

### generates array random numbers from normal distribution with center as 0

In [48]:
np.random.randn(4)

array([-0.83463208,  0.19150521, -0.80823649,  1.40700285])

In [51]:
np.random.randn(5,5)

array([[-1.52574048,  0.55458336,  0.46091076, -1.87316737,  0.24314149],
       [ 0.47479934, -0.42138044, -0.65110351,  0.31785727, -0.57452285],
       [ 0.21553748, -0.30334479,  1.65092707,  0.80085444, -1.31024769],
       [ 0.24764805,  0.14528897, -1.58406236,  1.20866621, -1.20127432],
       [-0.95753698,  0.44116444, -0.48566233,  1.21419469,  1.12412586]])

### generates array of random numbers between starting and ending

In [79]:
np.random.randint(0,5, (3,6))

array([[4, 2, 3, 1, 4, 3],
       [3, 2, 4, 0, 3, 0],
       [1, 0, 2, 4, 1, 4]], dtype=int32)

In [68]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
arr = np.random.randint(0,10, (3,8))

In [87]:
arr

array([[2, 7, 6, 1, 5, 9, 5, 4],
       [6, 6, 9, 1, 0, 2, 7, 9],
       [5, 6, 2, 3, 2, 8, 6, 0]], dtype=int32)

In [93]:
arr.flatten(order= 'f')

array([2, 6, 5, 7, 6, 6, 6, 9, 2, 1, 1, 3, 5, 0, 2, 9, 2, 8, 5, 7, 6, 4,
       9, 0], dtype=int32)

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# matrix
### arrangement of data in rectangular form
### rectangular matrix

In [97]:
np.random.randint(0,100, (5,3))

array([[55, 17, 63],
       [15,  3, 67],
       [18, 21, 25],
       [41, 29, 52],
       [26, 27, 62]], dtype=int32)

### square matrix

In [98]:
np.random.randint(0,100, (3,3))

array([[54, 57, 56],
       [51, 33, 86],
       [87, 20, 40]], dtype=int32)

### Triangle matrix
#### upper triangle matrix

In [99]:
np.array([
    [1,2,3],
    [0,4,5],
    [0,0,6]
])

array([[1, 2, 3],
       [0, 4, 5],
       [0, 0, 6]])

#### lower triangle matrix

In [100]:
np.array([
    [1,0,0],
    [2,3,0],
    [4,5,6]
])

array([[1, 0, 0],
       [2, 3, 0],
       [4, 5, 6]])

#### diagonal matrix

In [101]:
np.array([
    [1,0,0],
    [0,2,0],
    [0,0,3]
])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### Transpose of a matrix

In [102]:
np.random.randint(0,100, (3,3))

array([[94, 78, 27],
       [90, 44, 45],
       [52, 27, 13]], dtype=int32)

In [105]:
arr

array([[2, 7, 6, 1, 5, 9, 5, 4],
       [6, 6, 9, 1, 0, 2, 7, 9],
       [5, 6, 2, 3, 2, 8, 6, 0]], dtype=int32)

In [104]:
arr.transpose()

array([[2, 6, 5],
       [7, 6, 6],
       [6, 9, 2],
       [1, 1, 3],
       [5, 0, 2],
       [9, 2, 8],
       [5, 7, 6],
       [4, 9, 0]], dtype=int32)