In [2]:
import numpy as np

In [4]:
# seed function helps to retreive the same value in every system's array

## indexing

In [15]:
np.random.seed(50)

In [16]:
arr = np.random.randint(1,20, (3,3))

In [17]:
arr

array([[17,  1, 12],
       [14,  2,  5],
       [ 7,  6,  7]], dtype=int32)

In [18]:
arr[2]

array([7, 6, 7], dtype=int32)

In [20]:
arr[2][0]

np.int32(7)

In [21]:
arr

array([[17,  1, 12],
       [14,  2,  5],
       [ 7,  6,  7]], dtype=int32)

In [22]:
arr = np.random.randint(1,20,(3,5,4))

In [23]:
arr

array([[[14,  6,  3,  8],
        [16,  5, 15,  4],
        [ 7, 12, 18, 11],
        [10,  1,  7,  3],
        [16, 10,  4,  3]],

       [[13,  1,  4,  3],
        [11, 17, 15,  1],
        [ 1, 12,  8, 15],
        [14,  8,  5,  5],
        [ 1, 12,  1, 14]],

       [[14,  2, 10, 12],
        [ 6,  1, 16,  6],
        [ 7,  2,  5,  5],
        [13, 15,  5, 12],
        [ 1,  6,  9, 13]]], dtype=int32)

In [24]:
arr[1]

array([[13,  1,  4,  3],
       [11, 17, 15,  1],
       [ 1, 12,  8, 15],
       [14,  8,  5,  5],
       [ 1, 12,  1, 14]], dtype=int32)

In [26]:
arr[1,3,2]

np.int32(5)

In [28]:
arr[0]

array([[14,  6,  3,  8],
       [16,  5, 15,  4],
       [ 7, 12, 18, 11],
       [10,  1,  7,  3],
       [16, 10,  4,  3]], dtype=int32)

In [29]:
arr[0][2]

array([ 7, 12, 18, 11], dtype=int32)

In [30]:
arr[0][2][3]

np.int32(11)

## Slicing

In [4]:
arr = np.random.randint(1,20, (5,5))

In [5]:
arr

array([[17, 16,  4, 14, 11],
       [ 5, 10,  3, 17,  3],
       [ 5,  6, 16, 19,  2],
       [ 5, 11, 14,  8, 10],
       [12, 17,  1,  3,  8]], dtype=int32)

In [6]:
arr[2]

array([ 5,  6, 16, 19,  2], dtype=int32)

In [9]:
arr[2:4]

array([[ 5,  6, 16, 19,  2],
       [ 5, 11, 14,  8, 10]], dtype=int32)

In [10]:
arr[2:4, 1:3]

array([[ 6, 16],
       [11, 14]], dtype=int32)

In [11]:
arr[::-1]

array([[12, 17,  1,  3,  8],
       [ 5, 11, 14,  8, 10],
       [ 5,  6, 16, 19,  2],
       [ 5, 10,  3, 17,  3],
       [17, 16,  4, 14, 11]], dtype=int32)

In [56]:
arr

array([[ 17,  16,   4,  14,  11],
       [  5,  10,   3,  17,   3],
       [  5,   6,  16,  19,   2],
       [  5,  11,  -4,   8,  10],
       [ 12, -19,   1,   3,   8]], dtype=int32)

In [57]:
arr[2:4, 1:4]

array([[ 6, 16, 19],
       [11, -4,  8]], dtype=int32)

In [58]:
arr

array([[ 17,  16,   4,  14,  11],
       [  5,  10,   3,  17,   3],
       [  5,   6,  16,  19,   2],
       [  5,  11,  -4,   8,  10],
       [ 12, -19,   1,   3,   8]], dtype=int32)

In [70]:
arr[:,0:4]

array([[ 17,  16,   4,  14],
       [  5,  10,   3,  17],
       [  5,   6,  16,  19],
       [  5,  11,  -4,   8],
       [ 12, -19,   1,   3]], dtype=int32)

In [71]:
arr[-1,1]= -19

In [72]:
arr

array([[ 17,  16,   4,  14,  11],
       [  5,  10,   3,  17,   3],
       [  5,   6,  16,  19,   2],
       [  5,  11,  -4,   8,  10],
       [ 12, -19,   1,   3,   8]], dtype=int32)

In [73]:
arr[-1]

array([ 12, -19,   1,   3,   8], dtype=int32)

In [74]:
arr[-2]

array([ 5, 11, -4,  8, 10], dtype=int32)

In [86]:
arr[-2, 2] = -4

In [87]:
arr

array([[17, 16,  4, 14, 11],
       [ 5, 10,  3, 17,  3],
       [ 5,  5, 16, 19,  2],
       [ 5,  5, -4,  8, 10],
       [ 5,  5,  1,  3,  8]], dtype=int32)

In [88]:
arr

array([[17, 16,  4, 14, 11],
       [ 5, 10,  3, 17,  3],
       [ 5,  5, 16, 19,  2],
       [ 5,  5, -4,  8, 10],
       [ 5,  5,  1,  3,  8]], dtype=int32)

In [136]:
arr[2:]

array([[ 5,  5,  5, 19,  2],
       [ 5,  5,  5,  8, 10],
       [ 5,  5,  5,  3,  8]], dtype=int32)

In [137]:
arr[2:,0:2]

array([[5, 5],
       [5, 5],
       [5, 5]], dtype=int32)

In [138]:
arr[2:,0:2] = 5

In [139]:
arr

array([[17, 16,  4, 14, 11],
       [ 5, 10,  3, 17,  3],
       [ 5,  5,  5, 19,  2],
       [ 5,  5,  5,  8, 10],
       [ 5,  5,  5,  3,  8]], dtype=int32)

In [170]:
arr[-2:, -2]

array([8, 3], dtype=int32)

In [171]:
arr[-2:,-2:]

array([[ 8, 10],
       [ 3,  8]], dtype=int32)

In [172]:
a = arr[-2:, -2:]

In [173]:
a

array([[ 8, 10],
       [ 3,  8]], dtype=int32)

In [174]:
a[0]

array([ 8, 10], dtype=int32)

In [176]:
a[0, -1]

np.int32(10)

In [177]:
a[0, -1]= 100

In [178]:
a

array([[  8, 100],
       [  3,   8]], dtype=int32)

In [179]:
arr

array([[ 17,  16,   4,  14,  11],
       [  5,  10,   3,  17,   3],
       [  5,   5,   5,  19,   2],
       [  5,   5,   5,   8, 100],
       [  5,   5,   5,   3,   8]], dtype=int32)

In [309]:
arr = np.arange(9)
arr = arr.reshape(3,3)

In [310]:
a= arr

In [311]:
b= arr.copy()

In [314]:
a[1][2] = 50

In [315]:
a

array([[ 0,  1,  2],
       [ 3, 50, 50],
       [ 6,  7,  8]])

In [316]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [317]:
arr = np.arange(13)

In [318]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [329]:
arr = np.arange(12)
arr = arr.reshape(3,2,2)

In [330]:
arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [331]:
a = arr

In [332]:
b = arr.copy()

In [333]:
a[2][1]= 0

In [334]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]],

       [[8, 9],
        [0, 0]]])