In [1]:
import numpy as np

In [4]:
# seed function helps to retreive the same value in every system's array

## indexing

In [15]:
np.random.seed(50)

In [16]:
arr = np.random.randint(1,20, (3,3))

In [17]:
arr

array([[17,  1, 12],
       [14,  2,  5],
       [ 7,  6,  7]], dtype=int32)

In [18]:
arr[2]

array([7, 6, 7], dtype=int32)

In [20]:
arr[2][0]

np.int32(7)

In [21]:
arr

array([[17,  1, 12],
       [14,  2,  5],
       [ 7,  6,  7]], dtype=int32)

In [22]:
arr = np.random.randint(1,20,(3,5,4))

In [23]:
arr

array([[[14,  6,  3,  8],
        [16,  5, 15,  4],
        [ 7, 12, 18, 11],
        [10,  1,  7,  3],
        [16, 10,  4,  3]],

       [[13,  1,  4,  3],
        [11, 17, 15,  1],
        [ 1, 12,  8, 15],
        [14,  8,  5,  5],
        [ 1, 12,  1, 14]],

       [[14,  2, 10, 12],
        [ 6,  1, 16,  6],
        [ 7,  2,  5,  5],
        [13, 15,  5, 12],
        [ 1,  6,  9, 13]]], dtype=int32)

In [24]:
arr[1]

array([[13,  1,  4,  3],
       [11, 17, 15,  1],
       [ 1, 12,  8, 15],
       [14,  8,  5,  5],
       [ 1, 12,  1, 14]], dtype=int32)

In [26]:
arr[1,3,2]

np.int32(5)

In [28]:
arr[0]

array([[14,  6,  3,  8],
       [16,  5, 15,  4],
       [ 7, 12, 18, 11],
       [10,  1,  7,  3],
       [16, 10,  4,  3]], dtype=int32)

In [29]:
arr[0][2]

array([ 7, 12, 18, 11], dtype=int32)

In [30]:
arr[0][2][3]

np.int32(11)

## Slicing

In [33]:
arr = np.random.randint(1,20, (5,5))

In [34]:
arr

array([[ 7, 16,  1, 19, 12],
       [ 2, 18, 15, 15,  6],
       [ 7, 10,  5, 10,  1],
       [16, 17, 18, 17,  5],
       [12,  2,  6, 14,  4]], dtype=int32)

In [38]:
arr[2:4]

array([[ 7, 10,  5, 10,  1],
       [16, 17, 18, 17,  5]], dtype=int32)

In [39]:
arr[2:4, 1:3]

array([[10,  5],
       [17, 18]], dtype=int32)

In [40]:
arr[::-1]

array([[12,  2,  6, 14,  4],
       [16, 17, 18, 17,  5],
       [ 7, 10,  5, 10,  1],
       [ 2, 18, 15, 15,  6],
       [ 7, 16,  1, 19, 12]], dtype=int32)

In [41]:
arr

array([[ 7, 16,  1, 19, 12],
       [ 2, 18, 15, 15,  6],
       [ 7, 10,  5, 10,  1],
       [16, 17, 18, 17,  5],
       [12,  2,  6, 14,  4]], dtype=int32)

In [56]:
arr[2:4, 1:4]

array([[10,  5, 10],
       [17, 18, 17]], dtype=int32)

In [57]:
arr

array([[ 7, 16,  1, 19, 12],
       [ 2, 18, 15, 15,  6],
       [ 7, 10,  5, 10,  1],
       [16, 17, 18, 17,  5],
       [12,  2,  6, 14,  4]], dtype=int32)

In [60]:
arr[:,0:4]

array([[ 7, 16,  1, 19],
       [ 2, 18, 15, 15],
       [ 7, 10,  5, 10],
       [16, 17, 18, 17],
       [12,  2,  6, 14]], dtype=int32)

In [63]:
arr[-1,1] = -19

In [64]:
arr

array([[  7,  16,   1,  19,  12],
       [  2,  18,  15,  15,   6],
       [  7,  10,   5,  10,   1],
       [ 16,  17,  18,  17,   5],
       [ 12, -19,   6,  14,   4]], dtype=int32)

In [65]:
arr[-1]

array([ 12, -19,   6,  14,   4], dtype=int32)

In [69]:
arr[-2]

array([16, 17, 18, 17,  5], dtype=int32)

In [70]:
arr[-2, 2] = -4

In [71]:
arr

array([[  7,  16,   1,  19,  12],
       [  2,  18,  15,  15,   6],
       [  7,  10,   5,  10,   1],
       [ 16,  17,  -4,  17,   5],
       [ 12, -19,   6,  14,   4]], dtype=int32)

In [72]:
arr

array([[  7,  16,   1,  19,  12],
       [  2,  18,  15,  15,   6],
       [  7,  10,   5,  10,   1],
       [ 16,  17,  -4,  17,   5],
       [ 12, -19,   6,  14,   4]], dtype=int32)

In [73]:
arr[2:]

array([[  7,  10,   5,  10,   1],
       [ 16,  17,  -4,  17,   5],
       [ 12, -19,   6,  14,   4]], dtype=int32)

In [76]:
arr[2:, 0:2] = 5

In [77]:
arr

array([[ 7, 16,  1, 19, 12],
       [ 2, 18, 15, 15,  6],
       [ 5,  5,  5, 10,  1],
       [ 5,  5, -4, 17,  5],
       [ 5,  5,  6, 14,  4]], dtype=int32)

In [81]:
arr[-2:, -2]

array([17, 14], dtype=int32)

In [85]:
arr[-2:, -2:]

array([[17,  5],
       [14,  4]], dtype=int32)

In [86]:
a = arr[-2:, -2:]

In [87]:
a

array([[17,  5],
       [14,  4]], dtype=int32)

In [90]:
a[0]

array([17,  5], dtype=int32)

In [91]:
a[0, -1]

np.int32(5)

In [92]:
a[0, -1]= 100

In [93]:
a

array([[ 17, 100],
       [ 14,   4]], dtype=int32)

In [94]:
arr

array([[  7,  16,   1,  19,  12],
       [  2,  18,  15,  15,   6],
       [  5,   5,   5,  10,   1],
       [  5,   5,  -4,  17, 100],
       [  5,   5,   6,  14,   4]], dtype=int32)

In [101]:
arr = np.arange(9)
arr = arr.reshape(3,3)

In [102]:
a= arr

In [103]:
b= arr.copy()

In [105]:
a[0][0] = 50

In [106]:
a

array([[50,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [107]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])